# Generated by Django 4.1.7 on 2023-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('client', 'service', 'plan'), name='unique_subscription'),
        ),
    ]
